import React from 'react';
import {
  Folder, BookOpen, Home, Code2, Music, Camera,
  Globe, Lock, Heart, Zap, Inbox, User,
  Coffee, Palette, Plane, ShoppingBag,
  Martini, Utensils, Hamburger, Cake, ChefHat, Cpu, Leaf,
  ShoppingCart, Shirt, Handbag, BadgePercent, Network,
  BicepsFlexed, Dumbbell, Cloud, Monitor, CloudMoon, Club, Car, Van,
  Flag, FlaskRound, Tent, Ruler, ClipboardClock, Mail, Pencil, Drum, Guitar,
  Bug, MessageCircle,
} from 'lucide-react';
import { Icons } from '../components/ui/Icons';

const BriefcaseIcon = ({ style }: { style?: React.CSSProperties }) => (
  <Icons.briefcase size={typeof style?.width === 'number' ? style.width + 2 : 16} stroke={1.1} />
);

export const FOLDER_ICONS: Record<string, React.ComponentType<any>> = {
  Folder,
  Briefcase: BriefcaseIcon,
  BookOpen,
  Home,
  Code2,
  Music,
  Camera,
  Globe,
  Lock,
  Heart,
  Zap,
  Inbox,
  User,
  Coffee,
  Palette,
  Plane,
  ShoppingBag,
  Martini,
  Utensils,
  Hamburger,
  Cake,
  ChefHat,
  Cpu,
  Leaf,
  ShoppingCart,
  Shirt,
  Handbag,
  BadgePercent,
  Network,
  BicepsFlexed,
  Dumbbell,
  Cloud,
  Monitor,
  CloudMoon,
  Club,
  Car,
  Van,
  Flag,
  FlaskRound,
  Tent,
  Ruler,
  ClipboardClock,
  Mail,
  Pencil,
  Drum,
  Guitar,
  Bug,
  MessageCircle,
};
